version: '2'
services:
    codesnippetlibrary-app:
        image: codesnippetlibrary
        external_links:
            - codesnippetlibrary-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=CodeSnippetLibrary
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    codesnippetlibrary-mongodb:
        extends:
            file: mongodb.yml
            service: codesnippetlibrary-mongodb
