version: '2'
services:
    codesnippetlibrary-mongodb:
        container_name: codesnippetlibrary-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/CodeSnippetLibrary/mongodb/:/data/db/
